CREATE public SYNONYM HOTEL_ADMIN FOR ADMIN.HOTELADMINPACK;
CREATE public SYNONYM GUEST FOR ADMIN.USERPACK;
CREATE public SYNONYM EMPLOYEE FOR ADMIN.EMPLOYEEPACK;
CREATE public SYNONYM GET_ROOM_PHOTO FOR ADMIN.GET_ROOM_PHOTO;

