SELECT SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV', 'DB_UNIQUE_NAME') AS DB_UNIQUE_NAME,
       SYS_CONTEXT('USERENV', 'INSTANCE') AS INSTANCE_NAME
FROM DUAL;

SELECT * FROM ALL_SYNONYMS where owner = 'ADMIN';
SELECT * FROM USER_SYNONYMS;

SELECT *
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'A_ADD_EMPLOYEE';
--1
CREATE public SYNONYM A_ADD_EMPLOYEE FOR ADMIN.HotelAdminPackageCRUD.INSERTEMPLOYEE;
CREATE public SYNONYM A_UPDATE_Employee FOR ADMIN.HotelAdminPackageCRUD.UpdateEmployee;
CREATE public SYNONYM A_DELETE_Employee FOR ADMIN.HotelAdminPackageCRUD.DeleteEmployee;

--2
CREATE SYNONYM A_INSERT_GUEST FOR ADMIN.HotelAdminPackageCRUD.INSERTGUEST;
CREATE SYNONYM A_UPDATE_GUEST FOR ADMIN.HotelAdminPackageCRUD.UPDATEGUEST;
CREATE SYNONYM A_DELETE_GUEST FOR ADMIN.HotelAdminPackageCRUD.DELETEGUEST;

--3
CREATE SYNONYM A_INSERT_TARIFFTYPE FOR ADMIN.HotelAdminPackageCRUD.INSERTTARIFFTYPE;
CREATE SYNONYM A_UPDATE_TARIFFTYPE FOR ADMIN.HotelAdminPackageCRUD.UPDATETARIFFTYPE;
CREATE SYNONYM A_DELETE_TARIFFTYPE FOR ADMIN.HotelAdminPackageCRUD.DELETETARIFFTYPE;

--4
CREATE SYNONYM A_INSERT_BOOKING FOR ADMIN.HotelAdminPackageCRUD.INSERTBOOKING;
CREATE SYNONYM A_UPDATE_BOOKING FOR ADMIN.HotelAdminPackageCRUD.UPDATEBOOKING;
CREATE SYNONYM A_DELETE_BOOKING FOR ADMIN.HotelAdminPackageCRUD.DELETEBOOKING;

--5
CREATE SYNONYM A_INSERT_PHOTO FOR ADMIN.HotelAdminPackageCRUD.INSERTPHOTO;
CREATE SYNONYM A_UPDATE_PHOTO FOR ADMIN.HotelAdminPackageCRUD.UPDATEPHOTO;
CREATE SYNONYM A_DELETE_PHOTO FOR ADMIN.HotelAdminPackageCRUD.DELETEPHOTO;

--6
CREATE SYNONYM A_INSERT_ROOM FOR ADMIN.HotelAdminPackageCRUD.INSERTROOM;
CREATE SYNONYM A_UPDATE_ROOM FOR ADMIN.HotelAdminPackageCRUD.UPDATEROOM;
CREATE SYNONYM A_DELETE_ROOM FOR ADMIN.HotelAdminPackageCRUD.DELETEROOM;

--7
CREATE SYNONYM A_INSERT_ROOMTYPE FOR ADMIN.HotelAdminPackageCRUD.INSERTROOMTYPE;
CREATE SYNONYM A_UPDATE_ROOMTYPE FOR ADMIN.HotelAdminPackageCRUD.UPDATEROOMTYPE;
CREATE SYNONYM A_DELETE_ROOMTYPE FOR ADMIN.HotelAdminPackageCRUD.DELETEROOMTYPE;

--8
CREATE SYNONYM A_INSERT_SERVICE FOR ADMIN.HotelAdminPackageCRUD.INSERTSERVICE;
CREATE SYNONYM A_UPDATE_SERVICE FOR ADMIN.HotelAdminPackageCRUD.UPDATESERVICE;
CREATE SYNONYM A_DELETE_SERVICE FOR ADMIN.HotelAdminPackageCRUD.DELETESERVICE;

--9
CREATE SYNONYM A_INSERT_SERVICETYPE FOR ADMIN.HotelAdminPackageCRUD.INSERTSERVICETYPE;
CREATE SYNONYM A_UPDATE_SERVICETYPE FOR ADMIN.HotelAdminPackageCRUD.UPDATESERVICETYPE;
CREATE SYNONYM A_DELETE_SERVICETYPE FOR ADMIN.HotelAdminPackageCRUD.DELETESERVICETYPE;



drop SYNONYM A_Insert_Employee ;
drop public SYNONYM A_INSERT_EMPLOYEE ;
drop public SYNONYM A_ADD_EMPLOYEE ;
drop SYNONYM A_Update_Employee ;
drop SYNONYM A_Delete_Employee ;
