SELECT SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV', 'DB_UNIQUE_NAME') AS DB_UNIQUE_NAME,
       SYS_CONTEXT('USERENV', 'INSTANCE') AS INSTANCE_NAME
FROM DUAL;

SELECT * FROM ALL_SYNONYMS where TABLE_OWNER = 'ADMIN';


CREATE public SYNONYM HOTEL_ADMIN FOR ADMIN.HOTELADMINPACK;
CREATE public SYNONYM GUEST FOR ADMIN.USERPACK;
CREATE public SYNONYM EMPLOYEE FOR ADMIN.EMPLOYEEPACK;
CREATE public SYNONYM GET_ROOM_PHOTO FOR ADMIN.GET_ROOM_PHOTO;

